language: android
dist: 
jdk:
  - openjdk11
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

before_install:
- nvm install 16
- node --version
install:
- yarn install
android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
script:
- npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
- chmod +x gradlew
- cd android && ./gradlew assembleDebug
# generated by `travis deploy releases`
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-debug.apk
  on:
    tags: true

  after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/android/app/build/outputs