name: react-native-android-build-apk
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install npm dependencies
        run: |
          npm install
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '11'
          cache: 'gradle'
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install npm dependencies
        run: |
          npm install
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '11'
          cache: 'gradle'
      - name: Putting data google service json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
          run: echo $DATA > /home/runner/work/Alingan/Alingan/android/app/google-services.json
      - name: Putting data google service json
        env:
          DATA: ${{ secrets.DEVELOPMENT_ENV }}
          run: echo $DATA > /home/runner/work/Alingan/Alingan/.env
      - name: build bundle
        run: npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res 
      - run: cd android && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/
      - name: Releasing using Hub
        uses: actions/action-release-debugapk@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: android/app/build/outputs/apk/debug/
 
        